"""
Monitoring stack installation and configuration.

Handles:
- Installing Langfuse + SigNoz monitoring files to ~/.a-sdlc/monitoring/
- Cloning SigNoz repository for Docker deployment
- Updating ~/.claude/settings.json with Stop hooks and OTEL environment
- Configuring Langfuse API keys
- Verifying monitoring setup health
"""

import importlib.resources
import secrets
import shutil
import subprocess
from pathlib import Path

from a_sdlc.mcp_setup import load_claude_settings, save_claude_settings

MONITORING_DIR = Path.home() / ".a-sdlc" / "monitoring"
SIGNOZ_DIR = MONITORING_DIR / "signoz"
SIGNOZ_TAG = "v0.110.1"
SIGNOZ_REPO = "https://github.com/SigNoz/signoz.git"

LANGFUSE_HOOK_PATH = MONITORING_DIR / "langfuse-hook.py"
LANGFUSE_COMPOSE_PATH = MONITORING_DIR / "langfuse-compose.yaml"
LANGFUSE_ENV_PATH = MONITORING_DIR / "langfuse.env"
DOCKER_COMPOSE_PATH = MONITORING_DIR / "docker-compose.yaml"

# OTEL environment variables to set in settings.json
OTEL_ENV_VARS = {
    "CLAUDE_CODE_ENABLE_TELEMETRY": "1",
    "OTEL_METRICS_EXPORTER": "otlp",
    "OTEL_LOGS_EXPORTER": "otlp",
    "OTEL_EXPORTER_OTLP_PROTOCOL": "grpc",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
    "OTEL_LOG_TOOL_DETAILS": "1",
}

HOOK_COMMAND = f"uv run {LANGFUSE_HOOK_PATH}"


# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------


def check_docker_available() -> bool:
    """Check if docker and docker compose are available."""
    if not shutil.which("docker"):
        return False
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            timeout=10,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def check_git_available() -> bool:
    """Check if git is available."""
    return shutil.which("git") is not None


# ---------------------------------------------------------------------------
# File installation
# ---------------------------------------------------------------------------


def _generate_langfuse_env() -> str:
    """Generate langfuse.env content with fresh random secrets."""
    nextauth_secret = secrets.token_hex(32)
    encryption_key = secrets.token_hex(32)
    salt = secrets.token_hex(16)

    return f"""# Langfuse Configuration (auto-generated by a-sdlc)
# Based on: https://github.com/langfuse/langfuse/blob/main/docker-compose.yml

# --- Authentication & Encryption ---
NEXTAUTH_SECRET={nextauth_secret}
ENCRYPTION_KEY={encryption_key}
SALT={salt}
NEXTAUTH_URL=http://localhost:13000

# --- Database ---
DATABASE_URL=postgresql://langfuse:langfuse@langfuse-postgres:5432/langfuse

# --- ClickHouse ---
CLICKHOUSE_MIGRATION_URL=clickhouse://langfuse-clickhouse:9000
CLICKHOUSE_URL=http://langfuse-clickhouse:8123
CLICKHOUSE_USER=langfuse
CLICKHOUSE_PASSWORD=langfuse
CLICKHOUSE_CLUSTER_ENABLED=false

# --- Redis ---
REDIS_HOST=langfuse-redis
REDIS_PORT=6379
REDIS_AUTH=langfuseredis

# --- S3 / MinIO – Event upload (trace ingestion, critical!) ---
LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_EVENT_UPLOAD_REGION=auto
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=langfuse
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=langfuse123
LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://langfuse-minio:9000
LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/

# --- S3 / MinIO – Media upload ---
LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=langfuse
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=langfuse123
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://langfuse-minio:9000
LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/

# --- Initial Admin User (first login) ---
LANGFUSE_INIT_ORG_ID=local-org
LANGFUSE_INIT_ORG_NAME=Local
LANGFUSE_INIT_PROJECT_ID=claude-code
LANGFUSE_INIT_PROJECT_NAME=claude-code
LANGFUSE_INIT_USER_EMAIL=admin@langfuse.local
LANGFUSE_INIT_USER_PASSWORD=changeme123
LANGFUSE_INIT_USER_NAME=Admin

# --- Misc ---
TELEMETRY_ENABLED=true
LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
"""


def _generate_docker_compose() -> str:
    """Generate top-level docker-compose.yaml with includes."""
    return """# Claude Code Monitoring Stack (SigNoz + Langfuse)
# Auto-generated by `a-sdlc install --with-monitoring`
#
# Usage:
#   docker compose up -d        # Start all services
#   docker compose down          # Stop all services
#   docker compose ps            # Check status
#   docker compose down -v       # Stop and delete all data
#
# SigNoz Dashboard: http://localhost:8080
# Langfuse Dashboard: http://localhost:13000
# OTLP gRPC: localhost:4317
# OTLP HTTP: localhost:4318

include:
  - path: signoz/deploy/docker/docker-compose.yaml
  - path: langfuse-compose.yaml
"""


def install_monitoring_files(force: bool = False) -> tuple[bool, str]:
    """Install monitoring files to ~/.a-sdlc/monitoring/.

    Copies langfuse-compose.yaml and langfuse-hook.py from package data,
    generates langfuse.env with fresh secrets, and generates the top-level
    docker-compose.yaml.

    Args:
        force: If True, overwrite existing files.

    Returns:
        Tuple of (success, message)
    """
    try:
        MONITORING_DIR.mkdir(parents=True, exist_ok=True)

        # Copy langfuse-compose.yaml
        if force or not LANGFUSE_COMPOSE_PATH.exists():
            pkg_files = importlib.resources.files("a_sdlc.monitoring_files")
            compose_content = (pkg_files / "langfuse-compose.yaml").read_text()
            LANGFUSE_COMPOSE_PATH.write_text(compose_content)

        # Copy langfuse-hook.py
        if force or not LANGFUSE_HOOK_PATH.exists():
            pkg_files = importlib.resources.files("a_sdlc.monitoring_files")
            hook_content = (pkg_files / "langfuse-hook.py").read_text()
            LANGFUSE_HOOK_PATH.write_text(hook_content)
            LANGFUSE_HOOK_PATH.chmod(0o755)

        # Generate langfuse.env with fresh secrets
        if force or not LANGFUSE_ENV_PATH.exists():
            LANGFUSE_ENV_PATH.write_text(_generate_langfuse_env())

        # Generate top-level docker-compose.yaml
        if force or not DOCKER_COMPOSE_PATH.exists():
            DOCKER_COMPOSE_PATH.write_text(_generate_docker_compose())

        return True, f"Monitoring files installed to {MONITORING_DIR}"

    except OSError as e:
        return False, f"Failed to install monitoring files: {e}"


# ---------------------------------------------------------------------------
# SigNoz clone
# ---------------------------------------------------------------------------


def clone_signoz(
    target_dir: Path | None = None,
    tag: str = SIGNOZ_TAG,
    force: bool = False,
) -> tuple[bool, str]:
    """Clone SigNoz repository for Docker deployment.

    Args:
        target_dir: Directory to clone into (default: ~/.a-sdlc/monitoring/signoz/)
        tag: Git tag to clone (default: v0.110.1)
        force: If True, remove existing clone and re-clone.

    Returns:
        Tuple of (success, message)
    """
    if target_dir is None:
        target_dir = SIGNOZ_DIR

    if target_dir.exists() and not force:
        return True, f"SigNoz already cloned at {target_dir}"

    if target_dir.exists() and force:
        shutil.rmtree(target_dir)

    try:
        result = subprocess.run(
            [
                "git", "clone",
                "--depth", "1",
                "--branch", tag,
                SIGNOZ_REPO,
                str(target_dir),
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if result.returncode != 0:
            return False, f"git clone failed: {result.stderr.strip()}"

        return True, f"SigNoz {tag} cloned to {target_dir}"

    except subprocess.TimeoutExpired:
        return False, "git clone timed out (>5 minutes)"
    except FileNotFoundError:
        return False, "git not found. Please install git first."


# ---------------------------------------------------------------------------
# Settings.json merging
# ---------------------------------------------------------------------------


def _hook_already_registered(settings: dict) -> bool:
    """Check if the langfuse hook is already registered in settings."""
    hooks_config = settings.get("hooks", {})
    stop_hooks = hooks_config.get("Stop", [])

    for matcher_entry in stop_hooks:
        for hook in matcher_entry.get("hooks", []):
            command = hook.get("command", "")
            if "langfuse-hook.py" in command:
                return True

    return False


def update_settings_hooks(force: bool = False) -> tuple[bool, str]:
    """Append Langfuse Stop hook to settings.json.

    Appends to the hooks.Stop[] array without overwriting existing hooks.
    Detects duplicates by checking if any hook command contains
    'langfuse-hook.py'.

    Args:
        force: If True, re-add even if already present.

    Returns:
        Tuple of (success, message)
    """
    settings = load_claude_settings()

    if not force and _hook_already_registered(settings):
        return True, "Langfuse hook already registered"

    # Remove existing langfuse hook entry if force
    if force:
        stop_hooks = settings.get("hooks", {}).get("Stop", [])
        settings.setdefault("hooks", {})["Stop"] = [
            entry for entry in stop_hooks
            if not any(
                "langfuse-hook.py" in h.get("command", "")
                for h in entry.get("hooks", [])
            )
        ]

    # Build the new hook entry
    hook_entry = {
        "matcher": "",
        "hooks": [
            {
                "type": "command",
                "command": HOOK_COMMAND,
            }
        ],
    }

    settings.setdefault("hooks", {}).setdefault("Stop", []).append(hook_entry)

    try:
        save_claude_settings(settings)
        return True, "Langfuse Stop hook registered in settings.json"
    except OSError as e:
        return False, f"Failed to save settings: {e}"


def update_settings_environment(force: bool = False) -> tuple[bool, str]:
    """Merge OTEL environment variables into settings.json.

    Sets CLAUDE_CODE_ENABLE_TELEMETRY, OTEL_METRICS_EXPORTER,
    OTEL_LOGS_EXPORTER, OTEL_EXPORTER_OTLP_PROTOCOL,
    OTEL_EXPORTER_OTLP_ENDPOINT, and OTEL_LOG_TOOL_DETAILS.

    Without force, skips keys that already exist.

    Args:
        force: If True, overwrite existing environment keys.

    Returns:
        Tuple of (success, message)
    """
    settings = load_claude_settings()
    env = settings.setdefault("environment", {})

    added = []
    skipped = []
    for key, value in OTEL_ENV_VARS.items():
        if key in env and not force:
            skipped.append(key)
        else:
            env[key] = value
            added.append(key)

    if not added:
        return True, "OTEL environment already configured"

    try:
        save_claude_settings(settings)
        msg = f"Set {len(added)} OTEL environment variable(s)"
        if skipped:
            msg += f" (skipped {len(skipped)} existing)"
        return True, msg
    except OSError as e:
        return False, f"Failed to save settings: {e}"


# ---------------------------------------------------------------------------
# Langfuse key configuration
# ---------------------------------------------------------------------------


def configure_langfuse_keys(
    secret_key: str,
    public_key: str,
    host: str = "http://localhost:13000",
) -> tuple[bool, str]:
    """Add Langfuse API keys to settings.json environment.

    Args:
        secret_key: Langfuse secret key (sk-lf-...)
        public_key: Langfuse public key (pk-lf-...)
        host: Langfuse host URL

    Returns:
        Tuple of (success, message)
    """
    settings = load_claude_settings()
    env = settings.setdefault("environment", {})

    env["LANGFUSE_SECRET_KEY"] = secret_key
    env["LANGFUSE_PUBLIC_KEY"] = public_key
    env["LANGFUSE_HOST"] = host

    try:
        save_claude_settings(settings)
        return True, "Langfuse API keys configured in settings.json"
    except OSError as e:
        return False, f"Failed to save settings: {e}"


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_monitoring_setup() -> dict[str, bool | str]:
    """Verify monitoring files and configuration are in place.

    Returns:
        Dict with verification results for each component.
    """
    results: dict[str, bool | str] = {}

    # File checks
    results["monitoring_dir"] = MONITORING_DIR.exists()
    results["langfuse_compose"] = LANGFUSE_COMPOSE_PATH.exists()
    results["langfuse_hook"] = LANGFUSE_HOOK_PATH.exists()
    results["langfuse_env"] = LANGFUSE_ENV_PATH.exists()
    results["docker_compose"] = DOCKER_COMPOSE_PATH.exists()
    results["signoz_cloned"] = SIGNOZ_DIR.exists()

    # Settings checks
    settings = load_claude_settings()
    results["hook_registered"] = _hook_already_registered(settings)

    env = settings.get("environment", {})
    results["otel_configured"] = all(
        key in env for key in OTEL_ENV_VARS
    )
    results["langfuse_keys_configured"] = bool(
        env.get("LANGFUSE_SECRET_KEY") and env.get("LANGFUSE_PUBLIC_KEY")
    )

    # Overall readiness
    results["files_ready"] = all([
        results["langfuse_compose"],
        results["langfuse_hook"],
        results["langfuse_env"],
        results["docker_compose"],
        results["signoz_cloned"],
    ])
    results["settings_ready"] = all([
        results["hook_registered"],
        results["otel_configured"],
    ])
    results["ready"] = bool(results["files_ready"] and results["settings_ready"])

    return results


def check_services_health() -> dict[str, bool | str]:
    """Check if monitoring services are running and reachable.

    Returns:
        Dict with health status for Langfuse and SigNoz.
    """
    import urllib.error
    import urllib.request

    results: dict[str, bool | str] = {}

    # Check Langfuse (port 13000)
    try:
        req = urllib.request.Request("http://localhost:13000", method="HEAD")
        urllib.request.urlopen(req, timeout=5)
        results["langfuse_reachable"] = True
        results["langfuse_url"] = "http://localhost:13000"
    except (urllib.error.URLError, OSError):
        results["langfuse_reachable"] = False
        results["langfuse_url"] = "http://localhost:13000 (not reachable)"

    # Check SigNoz (port 8080)
    try:
        req = urllib.request.Request("http://localhost:8080", method="HEAD")
        urllib.request.urlopen(req, timeout=5)
        results["signoz_reachable"] = True
        results["signoz_url"] = "http://localhost:8080"
    except (urllib.error.URLError, OSError):
        results["signoz_reachable"] = False
        results["signoz_url"] = "http://localhost:8080 (not reachable)"

    results["services_running"] = bool(
        results["langfuse_reachable"] and results["signoz_reachable"]
    )

    return results


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def setup_monitoring(force: bool = False) -> tuple[bool, str, dict]:
    """Complete monitoring setup: install files, clone SigNoz, configure settings.

    Args:
        force: If True, force reinstall even if already configured.

    Returns:
        Tuple of (success, message, verification_results)
    """
    messages = []

    # Check prerequisites
    if not check_docker_available():
        return False, (
            "Docker is required for the monitoring stack.\n\n"
            "Please install Docker Desktop: https://www.docker.com/products/docker-desktop/"
        ), {}

    if not check_git_available():
        return False, (
            "Git is required to clone SigNoz.\n\n"
            "Please install git: https://git-scm.com/downloads"
        ), {}

    # Install monitoring files
    success, msg = install_monitoring_files(force=force)
    if not success:
        return False, msg, {}
    messages.append(msg)

    # Clone SigNoz
    success, msg = clone_signoz(force=force)
    if not success:
        return False, msg, {}
    messages.append(msg)

    # Register Stop hook
    success, msg = update_settings_hooks(force=force)
    if not success:
        return False, msg, {}
    messages.append(msg)

    # Set OTEL environment
    success, msg = update_settings_environment(force=force)
    if not success:
        return False, msg, {}
    messages.append(msg)

    # Verify
    verification = verify_monitoring_setup()

    return True, "\n".join(messages), verification
