"""
Linear MCP integration plugin for task storage.

Syncs tasks with Linear issue tracker, allowing bidirectional
updates between local SDLC workflow and Linear projects.
"""

from datetime import datetime

from a_sdlc.plugins.base import Task, TaskPlugin, TaskPriority, TaskStatus


class LinearPlugin(TaskPlugin):
    """Sync tasks with Linear issue tracker.

    This plugin integrates with Linear via MCP (Model Context Protocol),
    allowing Claude Code to create and manage Linear issues directly.

    Configuration:
        - api_key: Linear API key (from Settings > API)
        - team_id: Team identifier (e.g., 'ENG')
        - default_project: Optional default project for new issues
        - sync_on_create: Auto-sync new tasks to Linear (default: True)
        - sync_on_complete: Auto-update Linear on completion (default: True)
    """

    # Map SDLC priorities to Linear priority values (1=urgent, 4=low)
    PRIORITY_MAP = {
        TaskPriority.URGENT: 1,
        TaskPriority.HIGH: 2,
        TaskPriority.MEDIUM: 3,
        TaskPriority.LOW: 4,
    }

    # Map Linear priority values back to SDLC priorities
    PRIORITY_REVERSE_MAP = {v: k for k, v in PRIORITY_MAP.items()}

    # Map SDLC status to Linear state names
    STATUS_MAP = {
        TaskStatus.PENDING: "Backlog",
        TaskStatus.IN_PROGRESS: "In Progress",
        TaskStatus.BLOCKED: "Blocked",
        TaskStatus.COMPLETED: "Done",
        TaskStatus.CANCELLED: "Canceled",
    }

    def __init__(self, config: dict) -> None:
        """Initialize Linear plugin.

        Args:
            config: Configuration with api_key, team_id, etc.
        """
        super().__init__(config)

        self.api_key = config.get("api_key")
        self.team_id = config.get("team_id")
        self.default_project = config.get("default_project")
        self.sync_on_create = config.get("sync_on_create", True)
        self.sync_on_complete = config.get("sync_on_complete", True)

        # Local cache for offline support
        self._local_cache: dict[str, Task] = {}

    def _check_configured(self) -> None:
        """Verify plugin is properly configured."""
        if not self.api_key or not self.team_id:
            raise RuntimeError(
                "Linear plugin not configured. Run: a-sdlc plugins configure linear"
            )

    def _format_description(self, task: Task) -> str:
        """Format task description for Linear issue body."""
        parts = [task.description, ""]

        if task.requirement_id:
            parts.append(f"**Requirement:** {task.requirement_id}")

        if task.component:
            parts.append(f"**Component:** {task.component}")

        if task.files_to_modify:
            parts.append("\n**Files to Modify:**")
            for f in task.files_to_modify:
                parts.append(f"- `{f}`")

        if task.implementation_steps:
            parts.append("\n**Implementation Steps:**")
            for i, step in enumerate(task.implementation_steps, 1):
                parts.append(f"{i}. {step}")

        if task.success_criteria:
            parts.append("\n**Success Criteria:**")
            for criterion in task.success_criteria:
                parts.append(f"- [ ] {criterion}")

        parts.append("\n---")
        parts.append(f"_Generated by a-sdlc | Local ID: {task.id}_")

        return "\n".join(parts)

    def _call_linear_mcp(self, operation: str, **kwargs) -> dict:
        """Call Linear MCP server.

        This is a placeholder for actual MCP integration.
        In practice, this would use the Linear MCP server tools.

        Args:
            operation: MCP operation name
            **kwargs: Operation parameters

        Returns:
            Response from MCP server
        """
        # NOTE: This is a stub implementation.
        # Actual implementation would call:
        #   mcp__linear__create_issue
        #   mcp__linear__update_issue
        #   mcp__linear__list_issues
        #   mcp__linear__get_issue
        #
        # For now, we provide instructions for Claude Code to use directly.
        raise NotImplementedError(
            f"Linear MCP call: {operation}\n"
            f"Parameters: {kwargs}\n\n"
            "To execute this operation, use the Linear MCP tools directly in Claude Code."
        )

    def create_task(self, task: Task) -> str:
        """Create a task and optionally sync to Linear.

        If sync_on_create is True, creates a Linear issue and
        stores the external_id reference.
        """
        self._check_configured()

        # Generate local ID if not provided
        if not task.id:
            task.id = f"TASK-{len(self._local_cache) + 1:03d}"

        # Store locally first
        self._local_cache[task.id] = task

        if self.sync_on_create:
            # Build Linear issue creation data
            issue_data = {
                "title": task.title,
                "description": self._format_description(task),
                "teamId": self.team_id,
                "priority": self.PRIORITY_MAP.get(task.priority, 3),
            }

            if self.default_project:
                issue_data["projectName"] = self.default_project

            # NOTE: Actual sync would happen here via MCP
            # For now, provide instructions
            task.external_id = f"LINEAR-PENDING-{task.id}"

        return task.id

    def get_task(self, task_id: str) -> Task | None:
        """Retrieve a task by ID."""
        return self._local_cache.get(task_id)

    def list_tasks(self, status: TaskStatus | None = None) -> list[Task]:
        """List tasks, optionally filtered by status."""
        tasks = list(self._local_cache.values())

        if status is not None:
            tasks = [t for t in tasks if t.status == status]

        return sorted(tasks, key=lambda t: t.id)

    def update_task(self, task_id: str, updates: dict) -> None:
        """Update fields on a task."""
        task = self._local_cache.get(task_id)
        if task is None:
            raise KeyError(f"Task not found: {task_id}")

        # Apply updates
        for key, value in updates.items():
            if key == "status":
                task.status = TaskStatus(value) if isinstance(value, str) else value
            elif key == "priority":
                task.priority = TaskPriority(value) if isinstance(value, str) else value
            elif hasattr(task, key):
                setattr(task, key, value)

        task.updated_at = datetime.now()

        # If task has Linear ID, queue sync
        if task.external_id and not task.external_id.startswith("LINEAR-PENDING"):
            # NOTE: Would sync to Linear here
            pass

    def complete_task(self, task_id: str) -> None:
        """Mark a task as completed and sync to Linear."""
        task = self._local_cache.get(task_id)
        if task is None:
            raise KeyError(f"Task not found: {task_id}")

        task.status = TaskStatus.COMPLETED
        task.completed_at = datetime.now()
        task.updated_at = datetime.now()

        if self.sync_on_complete and task.external_id:
            # NOTE: Would update Linear issue status here
            pass

    def delete_task(self, task_id: str) -> None:
        """Delete a task."""
        if task_id not in self._local_cache:
            raise KeyError(f"Task not found: {task_id}")

        del self._local_cache[task_id]

    def sync_from_linear(self) -> int:
        """Pull updates from Linear to local cache.

        Returns:
            Number of tasks updated.
        """
        self._check_configured()
        # NOTE: Would fetch from Linear MCP here
        return 0

    def sync_to_linear(self) -> int:
        """Push local changes to Linear.

        Returns:
            Number of tasks synced.
        """
        self._check_configured()

        synced = 0
        for task in self._local_cache.values():
            if task.external_id and task.external_id.startswith("LINEAR-PENDING"):
                # Create new issue
                synced += 1
            # NOTE: Would create/update Linear issues here

        return synced

    def get_linear_instructions(self, task: Task) -> str:
        """Generate instructions for manual Linear issue creation.

        Returns:
            Markdown-formatted instructions for creating a Linear issue.
        """
        priority = self.PRIORITY_MAP.get(task.priority, 3)
        priority_label = {1: "Urgent", 2: "High", 3: "Medium", 4: "Low"}[priority]

        return f"""## Create Linear Issue

**To create this task in Linear, use the Linear MCP tool:**

```
Team: {self.team_id}
Title: {task.title}
Priority: {priority_label}
```

**Description:**

{self._format_description(task)}

---

After creating the issue, update the task with the Linear issue ID:
```
/sdlc:task link {task.id} <LINEAR-ISSUE-ID>
```
"""
