"""
Linear MCP integration plugin for task storage.

Syncs tasks with Linear issue tracker, allowing bidirectional
updates between local SDLC workflow and Linear projects.
Supports cycle (sprint) synchronization via Linear's GraphQL API.
"""

from datetime import datetime

from a_sdlc.plugins.base import (
    Sprint,
    Task,
    TaskPlugin,
    TaskPriority,
    TaskStatus,
)


class LinearPlugin(TaskPlugin):
    """Sync tasks with Linear issue tracker.

    This plugin integrates with Linear via MCP (Model Context Protocol),
    allowing Claude Code to create and manage Linear issues directly.

    Configuration:
        - api_key: Linear API key (from Settings > API)
        - team_id: Team identifier (e.g., 'ENG')
        - default_project: Optional default project for new issues
        - sync_on_create: Auto-sync new tasks to Linear (default: True)
        - sync_on_complete: Auto-update Linear on completion (default: True)
    """

    # Map SDLC priorities to Linear priority values (1=urgent, 4=low)
    PRIORITY_MAP = {
        TaskPriority.URGENT: 1,
        TaskPriority.HIGH: 2,
        TaskPriority.MEDIUM: 3,
        TaskPriority.LOW: 4,
    }

    # Map Linear priority values back to SDLC priorities
    PRIORITY_REVERSE_MAP = {v: k for k, v in PRIORITY_MAP.items()}

    # Map SDLC status to Linear state names
    STATUS_MAP = {
        TaskStatus.PENDING: "Backlog",
        TaskStatus.IN_PROGRESS: "In Progress",
        TaskStatus.BLOCKED: "Blocked",
        TaskStatus.COMPLETED: "Done",
        TaskStatus.CANCELLED: "Canceled",
    }

    def __init__(self, config: dict) -> None:
        """Initialize Linear plugin.

        Args:
            config: Configuration with api_key, team_id, etc.
        """
        super().__init__(config)

        self.api_key = config.get("api_key")
        self.team_id = config.get("team_id")
        self.default_project = config.get("default_project")
        self.sync_on_create = config.get("sync_on_create", True)
        self.sync_on_complete = config.get("sync_on_complete", True)

        # Local cache for offline support
        self._local_cache: dict[str, Task] = {}

    def _check_configured(self) -> None:
        """Verify plugin is properly configured."""
        if not self.api_key or not self.team_id:
            raise RuntimeError(
                "Linear plugin not configured. Run: a-sdlc plugins configure linear"
            )

    def _format_description(self, task: Task) -> str:
        """Format task description for Linear issue body."""
        parts = [task.description, ""]

        if task.requirement_id:
            parts.append(f"**Requirement:** {task.requirement_id}")

        if task.component:
            parts.append(f"**Component:** {task.component}")

        if task.files_to_modify:
            parts.append("\n**Files to Modify:**")
            for f in task.files_to_modify:
                parts.append(f"- `{f}`")

        if task.implementation_steps:
            parts.append("\n**Implementation Steps:**")
            for i, step in enumerate(task.implementation_steps, 1):
                parts.append(f"{i}. {step}")

        if task.success_criteria:
            parts.append("\n**Success Criteria:**")
            for criterion in task.success_criteria:
                parts.append(f"- [ ] {criterion}")

        parts.append("\n---")
        parts.append(f"_Generated by a-sdlc | Local ID: {task.id}_")

        return "\n".join(parts)

    def _call_linear_mcp(self, operation: str, **kwargs) -> dict:
        """Call Linear MCP server.

        This is a placeholder for actual MCP integration.
        In practice, this would use the Linear MCP server tools.

        Args:
            operation: MCP operation name
            **kwargs: Operation parameters

        Returns:
            Response from MCP server
        """
        # NOTE: This is a stub implementation.
        # Actual implementation would call:
        #   mcp__linear__create_issue
        #   mcp__linear__update_issue
        #   mcp__linear__list_issues
        #   mcp__linear__get_issue
        #
        # For now, we provide instructions for Claude Code to use directly.
        raise NotImplementedError(
            f"Linear MCP call: {operation}\n"
            f"Parameters: {kwargs}\n\n"
            "To execute this operation, use the Linear MCP tools directly in Claude Code."
        )

    def create_task(self, task: Task) -> str:
        """Create a task and optionally sync to Linear.

        If sync_on_create is True, creates a Linear issue and
        stores the external_id reference.
        """
        self._check_configured()

        # Generate local ID if not provided
        if not task.id:
            task.id = f"TASK-{len(self._local_cache) + 1:03d}"

        # Store locally first
        self._local_cache[task.id] = task

        if self.sync_on_create:
            # Build Linear issue creation data
            issue_data = {
                "title": task.title,
                "description": self._format_description(task),
                "teamId": self.team_id,
                "priority": self.PRIORITY_MAP.get(task.priority, 3),
            }

            if self.default_project:
                issue_data["projectName"] = self.default_project

            # NOTE: Actual sync would happen here via MCP
            # For now, provide instructions
            task.external_id = f"LINEAR-PENDING-{task.id}"

        return task.id

    def get_task(self, task_id: str) -> Task | None:
        """Retrieve a task by ID."""
        return self._local_cache.get(task_id)

    def list_tasks(self, status: TaskStatus | None = None) -> list[Task]:
        """List tasks, optionally filtered by status."""
        tasks = list(self._local_cache.values())

        if status is not None:
            tasks = [t for t in tasks if t.status == status]

        return sorted(tasks, key=lambda t: t.id)

    def update_task(self, task_id: str, updates: dict) -> None:
        """Update fields on a task."""
        task = self._local_cache.get(task_id)
        if task is None:
            raise KeyError(f"Task not found: {task_id}")

        # Apply updates
        for key, value in updates.items():
            if key == "status":
                task.status = TaskStatus(value) if isinstance(value, str) else value
            elif key == "priority":
                task.priority = TaskPriority(value) if isinstance(value, str) else value
            elif hasattr(task, key):
                setattr(task, key, value)

        task.updated_at = datetime.now()

        # If task has Linear ID, queue sync
        if task.external_id and not task.external_id.startswith("LINEAR-PENDING"):
            # NOTE: Would sync to Linear here
            pass

    def complete_task(self, task_id: str) -> None:
        """Mark a task as completed and sync to Linear."""
        task = self._local_cache.get(task_id)
        if task is None:
            raise KeyError(f"Task not found: {task_id}")

        task.status = TaskStatus.COMPLETED
        task.completed_at = datetime.now()
        task.updated_at = datetime.now()

        if self.sync_on_complete and task.external_id:
            # NOTE: Would update Linear issue status here
            pass

    def delete_task(self, task_id: str) -> None:
        """Delete a task."""
        if task_id not in self._local_cache:
            raise KeyError(f"Task not found: {task_id}")

        del self._local_cache[task_id]

    def sync_from_linear(self) -> int:
        """Pull updates from Linear to local cache.

        Returns:
            Number of tasks updated.
        """
        self._check_configured()
        # NOTE: Would fetch from Linear MCP here
        return 0

    def sync_to_linear(self) -> int:
        """Push local changes to Linear.

        Returns:
            Number of tasks synced.
        """
        self._check_configured()

        synced = 0
        for task in self._local_cache.values():
            if task.external_id and task.external_id.startswith("LINEAR-PENDING"):
                # Create new issue
                synced += 1
            # NOTE: Would create/update Linear issues here

        return synced

    def get_linear_instructions(self, task: Task) -> str:
        """Generate instructions for manual Linear issue creation.

        Returns:
            Markdown-formatted instructions for creating a Linear issue.
        """
        priority = self.PRIORITY_MAP.get(task.priority, 3)
        priority_label = {1: "Urgent", 2: "High", 3: "Medium", 4: "Low"}[priority]

        return f"""## Create Linear Issue

**To create this task in Linear, use the Linear MCP tool:**

```
Team: {self.team_id}
Title: {task.title}
Priority: {priority_label}
```

**Description:**

{self._format_description(task)}

---

After creating the issue, update the task with the Linear issue ID:
```
/sdlc:task link {task.id} <LINEAR-ISSUE-ID>
```
"""

    # ─────────────────────────────────────────────────────────────────────────
    # Cycle (Sprint) Operations
    # ─────────────────────────────────────────────────────────────────────────

    def list_cycles(self, status: str | None = None) -> list[dict]:
        """List Linear cycles (sprints) for the team.

        Args:
            status: Filter by status ("active", "upcoming", "completed")

        Returns:
            List of cycle dictionaries with id, name, startsAt, endsAt, issues

        Note:
            This method provides instructions for Claude Code to execute
            via Linear MCP or GraphQL API.
        """
        self._check_configured()

        # Linear GraphQL query for cycles
        query = """
        query Cycles($teamId: String!, $filter: CycleFilter) {
            team(id: $teamId) {
                cycles(filter: $filter) {
                    nodes {
                        id
                        name
                        number
                        startsAt
                        endsAt
                        progress
                        issues {
                            nodes {
                                id
                                identifier
                                title
                                state { name }
                                priority
                            }
                        }
                    }
                }
            }
        }
        """

        # NOTE: Actual implementation would use Linear MCP or GraphQL
        # Return instruction for Claude Code
        raise NotImplementedError(
            f"List Linear cycles\n\n"
            f"Team: {self.team_id}\n"
            f"Status filter: {status or 'all'}\n\n"
            f"To execute, use Linear MCP tools or the GraphQL API:\n"
            f"```graphql\n{query}\n```"
        )

    def get_cycle(self, cycle_id: str) -> dict | None:
        """Get a specific Linear cycle by ID.

        Args:
            cycle_id: Linear cycle ID

        Returns:
            Cycle dictionary with full details including issues
        """
        self._check_configured()

        query = """
        query Cycle($id: String!) {
            cycle(id: $id) {
                id
                name
                number
                startsAt
                endsAt
                progress
                issues {
                    nodes {
                        id
                        identifier
                        title
                        description
                        state { name }
                        priority
                        labels { nodes { name } }
                    }
                }
            }
        }
        """

        raise NotImplementedError(
            f"Get Linear cycle: {cycle_id}\n\n"
            f"Use Linear MCP tools or the GraphQL API:\n"
            f"```graphql\n{query}\n```"
        )

    def import_cycle_as_sprint(self, cycle_id: str) -> tuple[Sprint, list[Task]]:
        """Import a Linear cycle as a local sprint with tasks.

        Args:
            cycle_id: Linear cycle ID to import

        Returns:
            Tuple of (Sprint, list of Tasks)

        Note:
            This method provides instructions. The actual import is
            performed by Claude Code using the returned data structure.
        """
        self._check_configured()

        instructions = f"""## Import Linear Cycle as Sprint

**Step 1: Fetch cycle data**
Use Linear MCP to get cycle details:
- Cycle ID: {cycle_id}
- Team: {self.team_id}

**Step 2: Create local sprint**
```python
sprint = Sprint(
    id="",  # Will be generated
    name="<cycle name>",
    goal="<cycle description>",
    start_date=<cycle.startsAt>,
    end_date=<cycle.endsAt>,
    external_id="{cycle_id}",
    external_system="linear",
    external_url="https://linear.app/team/{self.team_id}/cycle/<number>"
)
```

**Step 3: Import issues as tasks**
For each issue in the cycle:
```python
task = Task(
    id="",  # Will be generated
    title="<issue.title>",
    description="<issue.description>",
    status=<map from issue.state>,
    priority=<map from issue.priority>,
    external_id="<issue.id>",
    external_url="<issue.url>"
)
```

**Step 4: Link sprint to cycle**
Save mapping in `.sdlc/sprints/mappings.json`
"""

        raise NotImplementedError(instructions)

    def sync_sprint_to_cycle(self, sprint: Sprint, tasks: list[Task]) -> dict:
        """Push local sprint status to Linear cycle.

        Args:
            sprint: Local sprint to sync
            tasks: Tasks in the sprint

        Returns:
            Sync result with changes made
        """
        self._check_configured()

        if not sprint.external_id:
            raise ValueError(f"Sprint {sprint.id} is not linked to a Linear cycle")

        # Build sync operations
        operations = []

        for task in tasks:
            if task.external_id:
                # Update existing issue
                linear_state = self.STATUS_MAP.get(task.status, "Backlog")
                operations.append({
                    "type": "update_issue",
                    "issue_id": task.external_id,
                    "changes": {
                        "state": linear_state,
                        "priority": self.PRIORITY_MAP.get(task.priority, 3)
                    }
                })
            else:
                # Create new issue in cycle
                operations.append({
                    "type": "create_issue",
                    "title": task.title,
                    "description": self._format_description(task),
                    "cycleId": sprint.external_id,
                    "priority": self.PRIORITY_MAP.get(task.priority, 3)
                })

        instructions = f"""## Sync Sprint to Linear Cycle

Sprint: {sprint.id} → Cycle: {sprint.external_id}

**Operations to perform:**

"""
        for op in operations:
            if op["type"] == "update_issue":
                instructions += f"- Update issue {op['issue_id']}: state={op['changes']['state']}\n"
            else:
                instructions += f"- Create issue: {op['title']}\n"

        instructions += f"""
**Execute using Linear MCP tools:**
1. For updates: Use `linear_update_issue` with issue ID and new state
2. For creates: Use `linear_create_issue` with cycleId parameter

Total operations: {len(operations)}
"""

        raise NotImplementedError(instructions)

    def sync_cycle_to_sprint(self, sprint: Sprint) -> dict:
        """Pull Linear cycle changes to local sprint.

        Args:
            sprint: Local sprint to update

        Returns:
            Dict with changes (new_tasks, updated_tasks, conflicts)
        """
        self._check_configured()

        if not sprint.external_id:
            raise ValueError(f"Sprint {sprint.id} is not linked to a Linear cycle")

        instructions = f"""## Sync Linear Cycle to Sprint

Cycle: {sprint.external_id} → Sprint: {sprint.id}

**Step 1: Fetch current cycle state**
Use Linear MCP to get all issues in cycle {sprint.external_id}

**Step 2: Compare with local tasks**
For each issue:
- If external_id matches local task: check for updates
- If no match: new issue added externally

**Step 3: Apply changes**
- Update task statuses from Linear states
- Create new tasks for new issues
- Flag conflicts (local changes vs Linear changes)

**Step 4: Update sync timestamp**
Record last_synced_at in mappings.json
"""

        raise NotImplementedError(instructions)

    def get_cycle_sync_instructions(self, cycle_id: str, sprint_id: str) -> str:
        """Generate complete sync instructions for a cycle-sprint pair.

        Returns human-readable instructions for bidirectional sync.
        """
        return f"""## Linear Cycle ↔ SDLC Sprint Sync

**Linked Resources:**
- Linear Cycle: {cycle_id}
- Local Sprint: {sprint_id}
- Team: {self.team_id}

### Pull Changes (Linear → Local)
```
/sdlc:sprint-sync-from {sprint_id}
```
This will:
1. Fetch current cycle state from Linear
2. Update local tasks with Linear status changes
3. Import any new issues as tasks

### Push Changes (Local → Linear)
```
/sdlc:sprint-sync-to {sprint_id}
```
This will:
1. Update Linear issues with local status changes
2. Create Linear issues for new local tasks
3. Update cycle progress

### Bidirectional Sync
```
/sdlc:sprint-sync {sprint_id}
```
This will:
1. Pull changes from Linear first
2. Resolve any conflicts (local wins by default)
3. Push local changes to Linear

### Status Mapping

| SDLC Status | Linear State |
|-------------|--------------|
| pending | Backlog |
| in_progress | In Progress |
| blocked | Blocked |
| completed | Done |
| cancelled | Canceled |
"""
