"""
Artifact storage plugins for a-sdlc.

Provides:
- Base artifact interface
- Artifact types and data structures
- Plugin discovery and loading
- Plugin manager for configuration

Artifacts are documentation outputs generated by /sdlc:scan,
such as codebase summaries, architecture diagrams, and data models.

Configuration is loaded from two locations (project config takes precedence):
1. Project config: .sdlc/config.yaml (in current directory)
2. Global config: ~/.config/a-sdlc/config.yaml (user-wide defaults)
"""

from pathlib import Path
from typing import Literal

import yaml

from a_sdlc.artifacts.base import Artifact, ArtifactPlugin, ArtifactType
from a_sdlc.artifacts.prd import PRD, PRDPlugin


def _deep_merge(base: dict, override: dict) -> dict:
    """Deep merge two dictionaries, with override taking precedence."""
    result = base.copy()
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


class ArtifactPluginManager:
    """Manages artifact storage plugins.

    Configuration is loaded from two locations:
    - Project config: .sdlc/config.yaml (takes precedence)
    - Global config: ~/.config/a-sdlc/config.yaml (fallback)
    """

    GLOBAL_CONFIG_FILE = Path.home() / ".config" / "a-sdlc" / "config.yaml"
    PROJECT_CONFIG_DIR = ".sdlc"
    PROJECT_CONFIG_FILE = "config.yaml"

    def __init__(self, project_dir: Path | None = None) -> None:
        """Initialize plugin manager.

        Args:
            project_dir: Project directory to look for .sdlc/config.yaml.
                        If None, uses current working directory.
        """
        self._plugins: dict[str, type[ArtifactPlugin]] = {}
        self._global_config: dict = {}
        self._project_config: dict = {}
        self._project_dir = project_dir or Path.cwd()
        self._load_builtin_plugins()
        self._load_config()

    @property
    def project_config_path(self) -> Path:
        """Get path to project config file."""
        return self._project_dir / self.PROJECT_CONFIG_DIR / self.PROJECT_CONFIG_FILE

    @property
    def _config(self) -> dict:
        """Get merged configuration (project overrides global)."""
        return _deep_merge(self._global_config, self._project_config)

    def _load_builtin_plugins(self) -> None:
        """Register built-in plugins."""
        from a_sdlc.artifacts.confluence import ConfluencePlugin
        from a_sdlc.artifacts.local import LocalArtifactPlugin

        self._plugins["local"] = LocalArtifactPlugin
        self._plugins["confluence"] = ConfluencePlugin

    def _load_config(self) -> None:
        """Load configuration from both global and project files."""
        # Load global config
        if self.GLOBAL_CONFIG_FILE.exists():
            with open(self.GLOBAL_CONFIG_FILE) as f:
                self._global_config = yaml.safe_load(f) or {}
        else:
            self._global_config = {}

        # Load project config
        if self.project_config_path.exists():
            with open(self.project_config_path) as f:
                self._project_config = yaml.safe_load(f) or {}
        else:
            self._project_config = {}

    def _save_config(
        self,
        target: Literal["global", "project"] = "project",
        config_updates: dict | None = None,
    ) -> None:
        """Save configuration to specified location."""
        if target == "global":
            config_file = self.GLOBAL_CONFIG_FILE
            current_config = self._global_config
        else:
            config_file = self.project_config_path
            current_config = self._project_config

        if config_updates:
            current_config = _deep_merge(current_config, config_updates)
            if target == "global":
                self._global_config = current_config
            else:
                self._project_config = current_config

        config_file.parent.mkdir(parents=True, exist_ok=True)
        with open(config_file, "w") as f:
            yaml.dump(current_config, f, default_flow_style=False)

    def list_plugins(self) -> list[str]:
        """List available plugin names."""
        return list(self._plugins.keys())

    def get_enabled_plugin(self) -> str:
        """Get the currently enabled plugin name."""
        return self._config.get("plugins", {}).get("artifacts", {}).get("provider", "local")

    def enable_plugin(
        self,
        name: str,
        target: Literal["global", "project"] = "project",
    ) -> None:
        """Enable a plugin by name.

        Args:
            name: Plugin name to enable.
            target: Where to save - "global" or "project" (default: project).

        Raises:
            ValueError: If plugin doesn't exist.
        """
        if name not in self._plugins:
            raise ValueError(f"Unknown plugin: {name}. Available: {', '.join(self._plugins.keys())}")

        config_updates = {"plugins": {"artifacts": {"provider": name}}}
        self._save_config(target=target, config_updates=config_updates)

    def configure_plugin(
        self,
        name: str,
        config: dict,
        target: Literal["global", "project"] = "project",
    ) -> None:
        """Configure a plugin.

        Args:
            name: Plugin name to configure.
            config: Plugin-specific configuration dict.
            target: Where to save - "global" or "project" (default: project).
        """
        config_updates = {"plugins": {"artifacts": {name: config}}}
        self._save_config(target=target, config_updates=config_updates)

    def get_plugin_config(self, name: str) -> dict:
        """Get configuration for a specific plugin.

        Merges global and project configs, with project taking precedence.

        Args:
            name: Plugin name.

        Returns:
            Plugin configuration dict.
        """
        return self._config.get("plugins", {}).get("artifacts", {}).get(name, {})

    def get_plugin(self, name: str | None = None) -> ArtifactPlugin:
        """Get an instantiated plugin.

        Args:
            name: Plugin name. If None, uses enabled plugin.

        Returns:
            Instantiated ArtifactPlugin.

        Raises:
            ValueError: If plugin doesn't exist.
        """
        if name is None:
            name = self.get_enabled_plugin()

        if name not in self._plugins:
            raise ValueError(f"Unknown plugin: {name}")

        plugin_class = self._plugins[name]
        config = self.get_plugin_config(name)

        return plugin_class(config)


# Global plugin manager instance
_artifact_plugin_manager: ArtifactPluginManager | None = None


def get_artifact_plugin_manager() -> ArtifactPluginManager:
    """Get the global artifact plugin manager instance."""
    global _artifact_plugin_manager
    if _artifact_plugin_manager is None:
        _artifact_plugin_manager = ArtifactPluginManager()
    return _artifact_plugin_manager


__all__ = [
    "Artifact",
    "ArtifactPlugin",
    "ArtifactPluginManager",
    "ArtifactType",
    "PRD",
    "PRDPlugin",
    "get_artifact_plugin_manager",
]
