"""
Base interface for artifact storage plugins.

All artifact storage backends must implement the ArtifactPlugin interface
to ensure consistent behavior across different storage mechanisms.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class ArtifactType(Enum):
    """Type of documentation artifact generated by /sdlc:scan."""

    CODEBASE_SUMMARY = "codebase-summary"
    ARCHITECTURE = "architecture"
    DATA_MODEL = "data-model"
    KEY_WORKFLOWS = "key-workflows"
    DIRECTORY_STRUCTURE = "directory-structure"
    REQUIREMENTS = "requirements"

    @classmethod
    def from_filename(cls, filename: str) -> "ArtifactType | None":
        """Get artifact type from filename.

        Args:
            filename: Artifact filename (e.g., 'architecture.md').

        Returns:
            ArtifactType if recognized, None otherwise.
        """
        name_map = {
            "codebase-summary": cls.CODEBASE_SUMMARY,
            "architecture": cls.ARCHITECTURE,
            "data-model": cls.DATA_MODEL,
            "key-workflows": cls.KEY_WORKFLOWS,
            "directory-structure": cls.DIRECTORY_STRUCTURE,
            "requirements": cls.REQUIREMENTS,
        }

        # Handle both .md and without extension
        base_name = filename.replace(".md", "")
        return name_map.get(base_name)

    def to_filename(self) -> str:
        """Get filename for this artifact type.

        Returns:
            Filename with .md extension.
        """
        return f"{self.value}.md"

    def to_title(self) -> str:
        """Get human-readable title.

        Returns:
            Title string (e.g., 'Codebase Summary').
        """
        return self.value.replace("-", " ").title()


@dataclass
class Artifact:
    """Represents a documentation artifact in the SDLC workflow.

    Artifacts are generated by /sdlc:scan and contain documentation
    about the codebase, such as architecture diagrams, data models,
    and workflow descriptions.
    """

    id: str
    artifact_type: ArtifactType
    title: str
    content: str  # Markdown content
    version: str = "1.0.0"
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    external_id: str | None = None  # ID in external system (e.g., Confluence page ID)
    external_url: str | None = None  # URL in external system
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert artifact to dictionary representation."""
        return {
            "id": self.id,
            "artifact_type": self.artifact_type.value,
            "title": self.title,
            "content": self.content,
            "version": self.version,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "external_id": self.external_id,
            "external_url": self.external_url,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Artifact":
        """Create artifact from dictionary representation."""
        return cls(
            id=data["id"],
            artifact_type=ArtifactType(data["artifact_type"]),
            title=data["title"],
            content=data["content"],
            version=data.get("version", "1.0.0"),
            created_at=datetime.fromisoformat(data["created_at"]) if "created_at" in data else datetime.now(),
            updated_at=datetime.fromisoformat(data["updated_at"]) if "updated_at" in data else datetime.now(),
            external_id=data.get("external_id"),
            external_url=data.get("external_url"),
            metadata=data.get("metadata", {}),
        )

    @classmethod
    def from_file(cls, filepath: str, content: str) -> "Artifact":
        """Create artifact from file content.

        Args:
            filepath: Path to artifact file.
            content: Markdown content.

        Returns:
            Artifact instance.
        """
        import os
        from pathlib import Path

        path = Path(filepath)
        filename = path.name
        artifact_type = ArtifactType.from_filename(filename)

        if artifact_type is None:
            # Default to codebase summary for unknown types
            artifact_type = ArtifactType.CODEBASE_SUMMARY

        # Extract title from first heading or use type
        title = artifact_type.to_title()
        for line in content.split("\n"):
            if line.startswith("# "):
                title = line[2:].strip()
                break

        return cls(
            id=filename.replace(".md", ""),
            artifact_type=artifact_type,
            title=title,
            content=content,
            updated_at=datetime.fromtimestamp(os.path.getmtime(filepath)) if os.path.exists(filepath) else datetime.now(),
        )


class ArtifactPlugin(ABC):
    """Base interface for artifact storage plugins.

    Plugins handle the storage and retrieval of documentation artifacts,
    whether that's local file storage or external documentation systems
    like Confluence.
    """

    def __init__(self, config: dict) -> None:
        """Initialize plugin with configuration.

        Args:
            config: Plugin-specific configuration dict.
        """
        self.config = config

    @abstractmethod
    def store_artifact(self, artifact: Artifact) -> str:
        """Store an artifact.

        Args:
            artifact: Artifact to store.

        Returns:
            Artifact ID (may be external ID if stored externally).
        """
        pass

    @abstractmethod
    def get_artifact(self, artifact_id: str) -> Artifact | None:
        """Retrieve an artifact by ID.

        Args:
            artifact_id: ID of artifact to retrieve.

        Returns:
            Artifact if found, None otherwise.
        """
        pass

    @abstractmethod
    def list_artifacts(self, artifact_type: ArtifactType | None = None) -> list[Artifact]:
        """List artifacts, optionally filtered by type.

        Args:
            artifact_type: Filter by this type. If None, returns all artifacts.

        Returns:
            List of artifacts matching criteria.
        """
        pass

    @abstractmethod
    def delete_artifact(self, artifact_id: str) -> None:
        """Delete an artifact.

        Args:
            artifact_id: ID of artifact to delete.

        Raises:
            KeyError: If artifact doesn't exist.
        """
        pass

    def update_artifact(self, artifact_id: str, content: str, version: str | None = None) -> None:
        """Update an existing artifact's content.

        Default implementation retrieves, modifies, and stores the artifact.
        Plugins may override for more efficient updates.

        Args:
            artifact_id: ID of artifact to update.
            content: New markdown content.
            version: New version string (optional).

        Raises:
            KeyError: If artifact doesn't exist.
        """
        artifact = self.get_artifact(artifact_id)
        if artifact is None:
            raise KeyError(f"Artifact not found: {artifact_id}")

        artifact.content = content
        artifact.updated_at = datetime.now()
        if version:
            artifact.version = version

        self.store_artifact(artifact)

    def sync_from_local(self, local_dir: str) -> int:
        """Sync artifacts from local .sdlc/artifacts/ directory.

        Args:
            local_dir: Path to local artifacts directory.

        Returns:
            Number of artifacts synced.
        """
        from pathlib import Path

        artifacts_dir = Path(local_dir)
        if not artifacts_dir.exists():
            return 0

        synced = 0
        for md_file in artifacts_dir.glob("*.md"):
            content = md_file.read_text()
            artifact = Artifact.from_file(str(md_file), content)
            self.store_artifact(artifact)
            synced += 1

        return synced
